import { TalentProfile } from "@/app/types";

export const MOCK_TALENT: TalentProfile[] = [
  {
    id: "1",
    name: "Maria Santos",
    bio: "Passionate culinary artist with over eight years of experience running a catering operation in Tagbilaran. Specializing in traditional Boholano cuisine and modern Filipino fusion, Maria has catered weddings, corporate events, and cultural festivals across the province.",
    skills: ["Catering", "Menu Planning", "Food Safety", "Event Coordination", "Filipino Cuisine"],
    aiTags: ["F&B", "Events", "Tagbilaran"],
    municipality: "Tagbilaran",
    availability: "available",
    matchScore: 94,
    matchReason: "94% — Strong F&B skill fit · Event catering background · Available now",
    badgeSource: "ai",
    externalLinks: [
      { label: "Portfolio", url: "https://mariasantosbohol.com" },
      { label: "Facebook", url: "https://facebook.com/mariasantosbohol" },
    ],
    email: "maria@bohol.ph",
    phone: "+63 917 123 4567",
    verifiedBadges: ["Sinulog Catering 2023"],
  },
  {
    id: "2",
    name: "Joven Reyes",
    bio: "Full-stack developer based in Panglao with a focus on building tourism-tech solutions. Joven has shipped mobile apps for resort booking, dive shop management, and local tour packages. Fluent in React, Node.js, and PostgreSQL.",
    skills: ["React", "Node.js", "PostgreSQL", "Mobile Development", "UX Design"],
    aiTags: ["Tech", "Tourism", "Panglao"],
    municipality: "Panglao",
    availability: "open-to-offers",
    matchScore: 88,
    matchReason: "88% — Full-stack skill match · Tourism tech experience · Open to offers",
    badgeSource: "ai",
    externalLinks: [
      { label: "GitHub", url: "https://github.com/jovenreyes" },
      { label: "Portfolio", url: "https://jovenreyes.dev" },
    ],
    email: "joven@bohol.ph",
    phone: "+63 918 234 5678",
    verifiedBadges: ["Panglao Dive App v2.0"],
  },
  {
    id: "3",
    name: "Ana Lim",
    bio: "Visual storyteller and brand designer with a decade of experience crafting identities for Bohol-based businesses. Ana's work spans hospitality, agriculture, and social enterprise. Her design philosophy draws heavily from Bohol's natural palette.",
    skills: ["Branding", "Graphic Design", "Photography", "Social Media", "Adobe Creative Suite"],
    aiTags: ["Design", "Branding", "Tagbilaran"],
    municipality: "Tagbilaran",
    availability: "available",
    matchScore: 82,
    matchReason: "82% — Design skill fit · Hospitality industry background · Available now",
    badgeSource: "ai",
    externalLinks: [
      { label: "Behance", url: "https://behance.net/analim" },
      { label: "Instagram", url: "https://instagram.com/analimbohol" },
    ],
    email: "ana@bohol.ph",
  },
  {
    id: "4",
    name: "Carlo Mendoza",
    bio: "Agricultural consultant and organic farming advocate from Carmen. Carlo has helped over 30 small-scale farmers in northern Bohol transition to sustainable practices, improving yields while reducing chemical dependency.",
    skills: ["Organic Farming", "Soil Science", "Irrigation", "Agri-Business", "Training & Facilitation"],
    aiTags: ["Agriculture", "Sustainability", "Carmen"],
    municipality: "Carmen",
    availability: "busy",
    matchScore: 71,
    matchReason: "71% — Agricultural skills match · Hands-on farm consulting · Currently busy",
    badgeSource: "self",
    externalLinks: [
      { label: "Facebook", url: "https://facebook.com/carlomendbohol" },
    ],
    email: "carlo@bohol.ph",
    phone: "+63 920 456 7890",
  },
  {
    id: "5",
    name: "Lena Flores",
    bio: "Event coordinator and hospitality professional with roots in Loboc. Lena manages cultural tourism events, river cruise experiences, and wedding packages along the Loboc River corridor.",
    skills: ["Event Management", "Hospitality", "Cultural Tourism", "Client Relations", "Logistics"],
    aiTags: ["Events", "Tourism", "Loboc"],
    municipality: "Loboc",
    availability: "available",
    matchScore: 77,
    matchReason: "77% — Events background · Tourism industry · Available now",
    badgeSource: "ai",
    externalLinks: [
      { label: "Website", url: "https://lobocevents.ph" },
      { label: "Facebook", url: "https://facebook.com/lobocevents" },
    ],
    email: "lena@bohol.ph",
    phone: "+63 921 567 8901",
    verifiedBadges: ["Loboc River Fiesta 2024"],
  },
  {
    id: "6",
    name: "Rodel Tan",
    bio: "Marine biologist and dive instructor turned eco-tourism entrepreneur. Rodel runs guided marine conservation dives and educational programs for resorts in Panglao, combining scientific rigor with engaging guest experiences.",
    skills: ["Marine Biology", "Scuba Instruction", "Eco-Tourism", "Research", "Public Speaking"],
    aiTags: ["Marine", "Tourism", "Panglao"],
    municipality: "Panglao",
    availability: "open-to-offers",
    matchScore: 65,
    matchReason: "65% — Niche skill match · Eco-tourism focus · Open to offers",
    badgeSource: "ai",
    externalLinks: [
      { label: "Website", url: "https://boholmarine.org" },
    ],
    email: "rodel@bohol.ph",
  },
];

export const POPULAR_TAGS = [
  { label: "Web Developer in Tagbilaran", query: "I need a web developer based in Tagbilaran" },
  { label: "Event Caterer", query: "Looking for an event caterer for a corporate event" },
  { label: "Graphic Designer", query: "Need a graphic designer for branding work" },
  { label: "Tour Guide Panglao", query: "Looking for a tour guide in Panglao" },
  { label: "Social Media Manager", query: "Need a social media manager for my business" },
  { label: "Organic Farmer Carmen", query: "Agricultural consultant or organic farmer in Carmen" },
  { label: "Photographer", query: "Need a photographer for an event" },
  { label: "Marine Biologist", query: "Eco-tourism expert or marine biologist" },
];

export const FEATURED_MUNICIPALITIES = [
  { name: "Panglao", description: "Island tourism & dive tech", count: 48 },
  { name: "Carmen", description: "Agriculture & eco-farming", count: 31 },
  { name: "Tagbilaran", description: "Business hub & creatives", count: 124 },
  { name: "Loboc", description: "Cultural tourism & events", count: 27 },
];

export const ENTITY_COLORS: Record<string, string> = {
  industry: "bg-violet-100 text-violet-800 border-violet-200",
  skill: "bg-sky-100 text-sky-800 border-sky-200",
  role: "bg-emerald-100 text-emerald-800 border-emerald-200",
  location: "bg-amber-100 text-amber-800 border-amber-200",
};
